name: Website Request
description: Request a website be excluded from the search
title: "[Request]: "
labels: ["request"]
assignees:
  - eiiot
body:
  - type: input
    id: website
    attributes:
      label: Website URL
      description: The URL of the website that you are requesting be blocked. Please include the question
      placeholder: ex. https://study.com/academy/answer/generally-if-the-concentration-or-temperature-of-the-reactants-were-increased-what-would-happen-to-the-enthalpy-diagram-what-would-happen-to-the-energies-of-reactants-products-and-activated-complex-and-to-the-rate.html
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reasoning
      description: Please describe why this website should be blacklisted (paywall, spam, etc)
  - type: textarea
    id: image
    attributes:
      label: Screenshot/Image
      description: Please upload a screenshot/image of the paywall/issue
